
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk
        sudo apt-get install -y gradle
    - name: Install Dependencies
      run: |
        gradle build
    - name: Build
      run: |
        gradle build
