
name: "Code Scanning - Action"
on:
  push
jobs:
  CodeQL-Build:
    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      security-events: write

      # only required for workflows in private repositories
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java

      # Build the project, including steps to (i) install tools (including compilers in the appropriate versions, 
      # package managers, and build tools), (ii) install dependencies, (iii) build the code.
      - name:
              uses: actions/checkout@v2
            - name: Install Gradle
              run: |
                sudo apt-get update
                sudo apt-get install gradle
            - name: Install Kotlin
              run: |
                sudo apt-get install kotlin
            - name: Install Tomcat
              run: |
                sudo apt-get install tomcat
            - name: Install Native Build Tools
              run: |
                sudo apt-get install native-build-tools
            - name: Set JVM arguments
              run: |
                echo org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8 >> gradle.properties
            - name: Set caching and parallel builds
              run: |
                echo org.gradle.caching=true >> gradle.properties
                echo org.gradle.parallel=true >> gradle.properties
            - name: Build project
              run: ./gradlew build


      # Analyze the project using CodeQL.
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
