
name: "Code Scanning - Action"
on:
  push
jobs:
  CodeQL-Build:
    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      security-events: write

      # only required for workflows in private repositories
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java

      # Build the project, including steps to (i) install tools (including compilers in the appropriate versions, 
      # package managers, and build tools), (ii) install dependencies, (iii) build the code.
      - name:
              uses: actions/checkout@v2
            - name: Install JDK 17
              run: sudo apt-get install openjdk-17-jdk
            - name: Install Gradle
              run: sudo apt-get install gradle
            - name: Install Kotlin compiler
              run: sudo apt-get install kotlinc
            - name: Install NoHttp plugin
              run: sudo apt-get install nohttp
            - name: Build project from source
              run: gradle build


      # Analyze the project using CodeQL.
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
